server:
  port: 9090

spring:
  kafka:
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
    producer:
      # 发送的对象信息变为json格式
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic:
    my-topic: my-topic
    my-topic2: my-topic2